#! /bin/sh

EBIN=../_build/default/lib/nodefinder/ebin

cleanup () {
  test -z "$erl" || kill $erl
}

erl -pa $EBIN -sname nodefinder_test1 -eval '
  {ok,_} = application:ensure_all_started (nodefinder),
  receive after 10000 -> ok end
' -noshell -noinput -s init stop &

erl=$!

trap cleanup INT QUIT TERM

sleep 1

erl -pa $EBIN -sname nodefinder_test2 -eval '
  "nodefinder_test2@" ++ Host = atom_to_list (node ()),
  [] = erlang:nodes (),
  {ok,_} = application:ensure_all_started (nodefinder),
  receive after 1000 -> ok end,
  Other = list_to_atom ("nodefinder_test1@" ++ Host),
  Ret = case erlang:nodes () of
     [ Other ] -> io:format("Test passed."), 0;
     _         -> io:format("Test failed."), 1
  end,
  rpc:call (Other, init, stop, []),
  halt(Ret)
' -noshell -noinput -s init stop || { cleanup; exit 1; }

wait

exit 0
