#! /bin/sh

#---------------------------------------------------------------------
#                             release-ok                              
# 
# This is the opportunity for the build type to reject the creation of
# a release package.  It is intended to identify build modes which are
# acceptable for creating test packages but not acceptable for release.
#---------------------------------------------------------------------

#---------------------------------------------------------------------
#                           chicken and egg                           
#---------------------------------------------------------------------

test -f "fw/sh/fw-find.sh" && fws="fw/sh/fw-find.sh"
test -f "fw.local/sh/fw-find.sh" && fws="fw.local/sh/fw-find.sh"
test ! -z "$fws" || {
  echo "C/release-ok: fatal: can't locate fw-find.sh" 1>&2
  exit 1
}

. "$fws"

#---------------------------------------------------------------------
#                              routines                               
#---------------------------------------------------------------------

fw_source "C/release-ok" "sh/fw-exec.sh"
fw_source "C/release-ok" "sh/parse-args.sh"
fw_source "C/release-ok" "sh/validate-args.sh"

#---------------------------------------------------------------------
#                                main                                 
#---------------------------------------------------------------------

fw_exec "build/automake/release-ok" "$@" || fatal "C/release-ok"

parse_args "C/release-ok" "$@"

validate_args "C/release-ok" "destdir" ""

if nm `find "$destdir" -type f` 2>/dev/null | grep -i gcov >/dev/null
  then
    echo "C/release-ok: error: coverage symbols detected"

    fatal "C/release-ok"
  fi

exit 0
